# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20190724_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='tenant_hash',
        ),
    ]
