# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_tenant_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='my_house',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='vacant',
            field=models.BooleanField(default=True),
        ),
    ]
