# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-25 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20190725_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='occupant',
        ),
    ]
