# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_remove_house_occupant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='house_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occupant', to='agent.House'),
        ),
    ]
