# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_auto_20190725_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('short_code', models.CharField(max_length=255, null=True)),
                ('meta', models.TextField(null=True)),
                ('house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rents', to='agent.House')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='agent.Tenant')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
